name: validate renovate.json

on:
  pull_request:

env:
  LOG_LEVEL: debug

jobs:
  renovate-config-validator:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: lts/*

      - run: npx -p renovate renovate-config-validator renovate.json5
